# ----------------------------------------------------------------------
# Project
# ----------------------------------------------------------------------

set(PROJECT_NAME myProject)
set(PROJECT_VERSION 1.0.0)
set(PROJECT_DESCRIPTION "A basic C project template")

# ----------------------------------------------------------------------
# Author
# ----------------------------------------------------------------------

set(PROJECT_AUTHOR "Nicola")
set(PROJECT_YEAR 2026)

# ----------------------------------------------------------------------
# Language
# ----------------------------------------------------------------------

set(C_STANDARD 11)

# ----------------------------------------------------------------------
# Features
# ----------------------------------------------------------------------

set(ENABLE_TESTS ON)
set(ENABLE_DOCS ON)